<a href="https://colab.research.google.com/github/Komal5578/ClinicPro/blob/main/feature_scaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 5 houses, 2 features: [sqft (in 1000s), bath count]
X = np.array([
    [1.0, 1],
    [1.5, 2],
    [2.0, 2],
    [2.5, 3],
    [3.0, 3]
])


y = np.array([20*1.0 + 10*1 + 5,
              20*1.5 + 10*2 + 5,
              20*2.0 + 10*2 + 5,
              20*2.5 + 10*3 + 5,
              20*3.0 + 10*3 + 5])

def compute_cost(X, y, w, b):
    m = len(y)
    predictions = X @ w + b
    errors = predictions - y
    cost = np.sum(errors ** 2) / (2 * m)
    return cost

def compute_gradients(X, y, w, b):
    m = len(y)
    predictions = X @ w + b
    errors = predictions - y
    dw = (X.T @ errors) / m
    db = np.sum(errors) / m
    return dw, db

In [2]:
mean = X.mean(axis=0)
std = X.std(axis=0)

X_scaled = (X - mean) / std
X_scaled

array([[-1.41421356, -1.60356745],
       [-0.70710678, -0.26726124],
       [ 0.        , -0.26726124],
       [ 0.70710678,  1.06904497],
       [ 1.41421356,  1.06904497]])

In [3]:
w = np.zeros(X_scaled.shape[1])
b = 0.0
learning_rate = 0.1
iterations = 1000

cost_history = []

for i in range(iterations):
    dw, db = compute_gradients(X_scaled, y, w, b)
    w = w - learning_rate * dw
    b = b - learning_rate * db

    cost = compute_cost(X_scaled, y, w, b)
    cost_history.append(cost)

    if i % 100 == 0:
        print(f"Iteration {i}: cost = {cost:.4f}, w = {w}, b = {b:.4f}")

print("\nFinal w:", w)
print("Final b:", b)

Iteration 0: cost = 1966.1893, w = [2.12132034 2.08463769], b = 6.7000
Iteration 100: cost = 0.2001, w = [12.23641547  9.38903492], b = 66.9984
Iteration 200: cost = 0.0663, w = [13.04527863  8.58017176], b = 67.0000
Iteration 300: cost = 0.0220, w = [13.51082821  8.11462219], b = 67.0000
Iteration 400: cost = 0.0073, w = [13.7787801  7.8466703], b = 67.0000
Iteration 500: cost = 0.0024, w = [13.93300258  7.69244781], b = 67.0000
Iteration 600: cost = 0.0008, w = [14.02176693  7.60368346], b = 67.0000
Iteration 700: cost = 0.0003, w = [14.07285618  7.55259422], b = 67.0000
Iteration 800: cost = 0.0001, w = [14.10226112  7.52318928], b = 67.0000
Iteration 900: cost = 0.0000, w = [14.11918544  7.50626496], b = 67.0000

Final w: [14.12885324  7.49659716]
Final b: 66.99999999999994


In [4]:
predictions = X_scaled @ w + b
predictions, y

(array([34.99748493, 55.0058422 , 64.99645013, 85.0048074 , 94.99541534]),
 array([35., 55., 65., 85., 95.]))